# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2666421318341022ee0dea47bebd83ca"
name = "render-app"
handle = "render-app-1"
application_url = "https://render-app-g5jk.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "appcarto.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
